name: users_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  shared_preferences: ^2.2.2

  image_picker: ^1.0.5
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - images/
    - slider/

  fonts:
    - family: Acme
      fonts:
        - asset: assets/fonts/Acme-Regular.ttf
    - family: KiwiMaru
      fonts:
        - asset: assets/fonts/KiwiMaru-Medium.ttf
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: TrainOne
      fonts:
        - asset: assets/fonts/TrainOne-Regular.ttf
    - family: Varela
      fonts:
            - asset: assets/fonts/VarelaRound-Regular.ttf


